using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace YahtzeeWPF2
{
    /// <summary>
    /// The int values correspond to the scoretable columns.
    /// </summary>
    enum Player
    {
        PlayerOne, PlayerTwo, PlayerThree,
    }


    /// <summary>
    /// The int values correspond to the dice throws remaining.
    /// </summary>
    enum Roll
    { Third, Second, First }


    /// <summary>
    ///  The int values of the enum map to the score table row index.
    /// </summary>
    enum Row
    {
        Ones, Twos, Threes, Fours, Fives, Sixes,
        Score63, ScoreUpper,
        ThreeX, FourX, FullHouse, FourStr, FiveStr, Chance,
        FiveX1, FiveX2, FiveX3, FiveX4,
        ScoreFiveX, ScoreLower, ScoreTotal
    }


    //struct ResultsItem
    //{
    //    Row Row;
    //    int Value;
    //}


    struct GameClock
    {
        public Player PlayerUp;
        public Roll DiceThrown;
        public int Round;
    }


    /// <summary>
    /// Key and Filled generated by GameModel
    /// Value generated by GameScore
    /// Supply data to Vim
    /// </summary>
    struct ScoringItem
    {
        public Row Row;
        public bool IsFilled;
        public int Value;
    }







    static class GameModel1
    {
        // Fields


        // Constructor


        // Properties

        /// <summary>
        /// How many times the dice have been rolled, this turn.
        /// </summary>
        public static int CurrentDiceRoll
        {
            get => GameClock.diceRoll;
        }

        /// <summary>
        ///  The player with the dice.
        /// </summary>
        static Player PlayerUp
        {
            get => GameClock.player;
        }

        /// <summary>
        /// 
        /// </summary>
        static int GameRound
        {
            get => GameClock.gameRound;
        }


        //static int? [] [] ScoreTable
        //{
        //    get => GameScores.scoreTable;
        //}




        #region Methods

        /* Reset GameClock and ScoreTable
         * 
         */
        public static void NewGame ()
        {
            GameClock.NewGame ();
            GameScores.NewGame ();
            GameDice.NewDice ();
            GameScoring.UpdateGameRows ();
        }


        public static void NextPlayer ()
        {
            GameClock.NextPlayer ();
            GameDice.NewDice ();
            GameScoring.UpdateGameRows ();
        }

        /* 
         * Record score in scoresheet, 
         * return scoring results to Vim for Vis,
         * RowEnum and value for each score sheet entry changed or updated.
         * ie Score taken and Totals and Bonuses.
         * */
        public static void RecordScore ( ScoringItem scoringItem )
        //public static List < string > [] [] RecordScore ( string [] scoreTaken )
        {
            List<ScoringItem> ResultsList = GameScores.RecordScore ( scoringItem, GameClock.player );
        }


        /* Advance game clock;
         * 
         * Call for roll unheld dice.
         * */
        public static void RollDice ()
        {
            GameClock.NextDiceRoll ();
            GameDice.RollDice ();
            GameScoring.UpdateGameRows ();
        }


        static void GenerateScoreList ()
        {

        }






        #endregion Methods







        private static class GameClock
        {
            public static int gameRound;
            public static int diceRoll;
            public static Player player;

            public static int GameRound
            {
                get => gameRound;
            }


            static void GameOver ()
            {
                //NYI
            }


            static void MustTakeScore ()
            {
                //NYI
            }


            public static void NewGame ()
            {
                gameRound = 1;
                diceRoll = 1;
                player = Player.PlayerOne;
            }


            public static void NextPlayer ()
            {
                diceRoll = 1;
                if ( player == Player.PlayerThree )
                {
                    player = Player.PlayerOne;
                    gameRound++;

                    if ( gameRound > 17 )
                        throw new Exception ( $"GameRound {gameRound} is greater than max of 17." );

                    //TODO:  Perform this check elsewhere??????????????????????????????????????????????????????????????????????????????????????????????????????????
                    if ( gameRound == 17 )
                        GameOver ();
                }
                else
                    player = ( Player ) ( ( ( int ) player ) + 1 );
            }


            public static void NextDiceRoll ()
            {
                diceRoll++;

                if ( diceRoll > 3 )
                {
                    throw new Exception ( $"DiceRoll = {diceRoll} is greater than max of 3." );
                }

                //TODO:  Perform this check elsewhere????????????????????????????????????????????????????????????????????????????????????????????????????????????
                if ( diceRoll == 3 )
                {
                    MustTakeScore ();
                }
            }

        }


        private static class GameScores
        {
            // Field

            // Three player columns with a row for each Row enum; 21 total.
            static int? [] [] scoreTable;

            // Public Methods

            public static void NewGame ()
            {
                scoreTable = new int? [ 3 ] [];
                for ( int i = 0; i < 3; i++ )
                {
                    scoreTable [ i ] = new int? [ 21 ];
                    //NOTE:  Initializing the "Score" rows to zero would eliminate many checks for null.
                }
            }

            /// <summary>
            /// Updates the score table, 
            /// Returns all entries that have changed for the Vis
            /// </summary>
            /// <param name="item"></param>
            /// <returns></returns>
            public static List<ScoringItem> RecordScore ( ScoringItem item, Player player )
            {
                //int scoreDelta = item.Value;
                // Get this players scores.
                int? [] scores = scoreTable [ ( int ) player ];
                //int _row = ( int ) item.Row;
                var resultsList = new List<ScoringItem> ();

                if ( scores [ ( int ) item.Row ] != null )
                {
                    throw new Exception ( "ERROR:  Only unfilled rows can be chosen." );
                }

                // Update the player chosen entry.
                AddToScores ( item.Row, item.Value, ref scores, ref resultsList );

                UpdatePostings ( item.Row, item.Value, ref scores, ref resultsList );

                scoreTable [ ( int ) player ] = scores;
                return resultsList;
            }


            // Private Methods

            // Do I need to ref the list ???????????????????????????????????????????????????????????????????????????????????????????????????????????????????
            static void AddToScores ( Row row, int value, ref int? [] scores, ref List<ScoringItem> resultsList )
            {
                AddToScoreTable ( row, value, ref scores );
                AddToScoringItemList ( row, value, ref resultsList );
            }


            // Do I need to ref the list ???????????????????????????????????????????????????????????????????????????????????????????????????????????????????
            static void AddToScoreTable ( Row row, int value, ref int? [] scores )
            {
                if ( scores [ ( int ) row ] == null )
                {
                    // Update the player's selected entry or an initial "Score" posting.
                    scores [ ( int ) row ] = value;
                }
                else
                {
                    // Update a "Score" posting.
                    scores [ ( int ) row ] += value;
                }
            }


            // Do I need to ref the list ???????????????????????????????????????????????????????????????????????????????????????????????????????????????????
            static void AddToScoringItemList ( Row row, int value, ref List<ScoringItem> resultsList )
            {
                var thisItem = new ScoringItem
                {
                    Row = row,
                    Value = value,
                };
                resultsList.Add ( thisItem );
            }


            static void CheckForBonus63 ( int? [] scores )
            {
                if ( ( scores [ ( int ) Row.ScoreUpper ] > 63 ) && ( scores [ ( int ) Row.Score63 ] == null ) )
                {
                    scores [ ( int ) Row.Score63 ] = 35;
                    scores [ ( int ) Row.ScoreUpper ] += 35;
                    scores [ ( int ) Row.ScoreTotal ] += 35;

                }

            }



            static void UpdatePostings ( Row row, int value, ref int? [] scores, ref List<ScoringItem> resultsList )
            {
                if ( ( int ) row <= ( int ) Row.Sixes )
                {
                    // Update the upper section postings.
                    UpdateUpperSection ( value, ref scores, ref resultsList );
                }

                else
                // Update the lower section postings.
                {
                    UpdateLowerSection ( row, value, ref scores, ref resultsList );
                }
            }


            static void UpdateUpperSection ( int value, ref int? [] scores, ref List<ScoringItem> resultsList )
            {
                // If the upper total is over 63 and the bonus63 has not been claimed previously.
                if ( ( ( value + ( scores [ ( int ) Row.ScoreUpper ] ?? 0 ) ) > 63 )
                    && ( scores [ ( int ) Row.Score63 ] == null ) )
                {
                    // Score the upper bonus with this Documented Magic Number.
                    int valueScore63 = 35;
                    AddToScores ( Row.Score63, valueScore63, ref scores, ref resultsList );
                    value += valueScore63;
                }

                AddToScores ( Row.ScoreUpper, value, ref scores, ref resultsList );
                AddToScores ( Row.ScoreTotal, value, ref scores, ref resultsList );
            }


            static void UpdateLowerSection ( Row row, int value, ref int? [] scores, ref List<ScoringItem> resultsList )
            {
                // Update the lower section.
                if ( ( ( int ) row >= ( int ) Row.FiveX1 ) && ( ( int ) row <= ( int ) Row.FiveX4 ) && ( value != 0 ) )
                {
                    // If a five of a kind was chosen, but not scratched.
                    AddToScores ( Row.ScoreFiveX, value, ref scores, ref resultsList );
                }

                AddToScores ( Row.ScoreLower, value, ref scores, ref resultsList );
                AddToScores ( Row.ScoreTotal, value, ref scores, ref resultsList );
            }

            //  VVVV  End of GameScores class.    VVVV
        }





    }
}
